Dev
Studio-23-xyz/com.studio23.ss2.settings.audio.fmod pull request #1
Opened 2024-03-25 11:02 UTC by dipokDipu

2024-03-25 11:05 UTC, pizzaandpineapples commented on Assets/Packages/com.studio23.ss2.settings.audio.fmod/Editor/CreateFModBusEnumEditor.cs
Remove this file

2024-03-25 11:20 UTC, pizzaandpineapples approved these changes

2024-03-25 19:47 UTC, Warhammer4000 requested changes
1) First of all remove upmassistant. It's not needed.
2) Why are there URP asset templates on Sound settings package?
3) Why is there a sample at root? If dependent package sample is required add it to the samples.
4) Textmeshpro should be inside Samples.
5) Tutorial Info? Dafaq
6) Settings ? Whut?
7) Add Branch Protection rule.
8) Forgot to add Repository url/section in the package.json

2024-04-08 07:42 UTC, pizzaandpineapples commented on Assets/Packages/com.studio23.ss2.settings.audio.fmod/Samples/Demo/Scripts/LabeledSlider.cs
> +                if (!_makeUpdateImmedietly) return;
rename to updateImmediately

2024-04-08 08:02 UTC, BDeshiDev approved these changes

2024-04-08 08:04 UTC, merged